import type { Metadata } from "next";
import { LegalPageLayout } from "@/components/legal/LegalPageLayout";

export const metadata: Metadata = {
  title: "Disclaimer | HomeSystemBuilder",
  description:
    "General and AI disclaimers for HomeSystemBuilder tools and printables. Informational use only.",
  robots: "index, follow",
};

export default function DisclaimerPage() {
  return (
    <LegalPageLayout
      title="Disclaimer"
      description="Please read these disclaimers before using our tools or printables."
    >
      <section className="mb-10" style={{ marginBottom: "var(--space-10)" }}>
        <h2
          className="mb-4 font-display text-xl font-semibold text-ink"
          style={{ marginBottom: "var(--space-4)" }}
        >
          General Disclaimer
        </h2>
        <p className="mb-4 font-body text-ink-muted" style={{ marginBottom: "var(--space-4)" }}>
          The tools and content on HomeSystemBuilder are for <strong>informational purposes only</strong>.
          Printable planners and schedules are productivity aids to help you organize your household.
          They are not a substitute for professional advice (e.g., legal, financial, medical, or
          cleaning services). Results will vary depending on your situation.
        </p>
      </section>

      <section className="mb-10" style={{ marginBottom: "var(--space-10)" }}>
        <h2
          className="mb-4 font-display text-xl font-semibold text-ink"
          style={{ marginBottom: "var(--space-4)" }}
        >
          AI Disclaimer
        </h2>
        <p className="font-body text-ink-muted" style={{ lineHeight: "var(--leading-relaxed)" }}>
          Outputs generated by AI or automated systems may contain errors and should not be
          considered professional advice. Use generated routines and planners as a starting point
          only. Always use your own judgment and adapt recommendations to your household
          conditions and safety requirements.
        </p>
      </section>

      <section>
        <h2
          className="mb-4 font-display text-xl font-semibold text-ink"
          style={{ marginBottom: "var(--space-4)" }}
        >
          Limitation of Liability
        </h2>
        <p className="font-body text-ink-muted" style={{ lineHeight: "var(--leading-relaxed)" }}>
          Users assume full responsibility for the use of generated routines, printables, or any
          data obtained from this site. Albor Digital LLC and HomeSystemBuilder are not liable for
          any loss, damage, or injury arising from reliance on our tools or content. See our
          Terms of Service for full limitations.
        </p>
      </section>
    </LegalPageLayout>
  );
}
